[package]
name = "bzl_gen_python_extractor"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.78"
tokio = { version = "1.35.1", features = ["full"] }
clap = { version = "4.4.12", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
walkdir = "2.4.0"
futures = "0.3.30"
sha2 = { version = "0.10.8", features = ["asm"] }
thiserror = "1.0.53"
lazy_static = "1.4.0"
ignore = "0.4.21"
rustpython-parser = { git = "https://github.com/RustPython/RustPython.git", rev = "b9ed63ed326e4ab9c97d808271ddc1d7ca05fda7"}
rustpython-ast = { git = "https://github.com/RustPython/RustPython.git", rev = "b9ed63ed326e4ab9c97d808271ddc1d7ca05fda7", features = ["unparse"]}
pretty_env_logger = "0.5.0"
log = "0.4.20"
encoding_rs = "0.8.33"
regex = "1.10.2"

[dev-dependencies]
tempfile = "3.9.0"

[dependencies.bzl_gen_build_shared_types]
path = "../shared_types"


[dependencies.bzl_gen_build_python_utilities]
path = "../python_utilities"
