[package]
name = "bzl_gen_jarscanner"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6.5"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
clap = { version = "4.1.11", features = ["derive"] }
tokio = { version = "1.28.0", features = ["full"] }
