[package]
name = "bzl_gen_jarscanner"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6.6"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
clap = { version = "4.4.12", features = ["derive"] }
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["full"] }

[dependencies.bzl_gen_build_shared_types]
path = "../shared_types"
