[package]
name = "bzl_gen_jarscanner"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "1.1.1"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
clap = { version = "4.5.4", features = ["derive"] }
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["full"] }

[dependencies.bzl_gen_build_shared_types]
path = "../shared_types"
