[package]
name = "bzl_gen_jarscanner"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6.6"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
clap = { version = "4.4.7", features = ["derive"] }
tempfile = "3.8.1"
tokio = { version = "1.33.0", features = ["full"] }

[dependencies.bzl_gen_build_shared_types]
path = "../shared_types"
