[package]
name = "bzl_gen_jarscanner"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6.6"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
clap = { version = "4.5.1", features = ["derive"] }
tempfile = "3.10.1"
tokio = { version = "1.36.0", features = ["full"] }

[dependencies.bzl_gen_build_shared_types]
path = "../shared_types"
