[package]
name = "bzl_gen_build_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.4.1", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
walkdir = "2.3.3"
futures = "0.3.28"
sha2 = { version = "0.10.7", features = ["asm"] }
thiserror = "1.0.47"
lazy_static = "1.4.0"
ignore = "0.4.18"
rustpython-parser = { git = "https://github.com/RustPython/RustPython.git", rev = "b9ed63ed326e4ab9c97d808271ddc1d7ca05fda7"}
rustpython-ast = { git = "https://github.com/RustPython/RustPython.git", rev = "b9ed63ed326e4ab9c97d808271ddc1d7ca05fda7", features = ["unparse"]}
pretty_env_logger = "0.5.0"
log = "0.4.20"

[dev-dependencies]
tempfile = "3.8.0"

[dependencies.bzl_gen_build_shared_types]
path = "../shared_types"

[dependencies.bzl_gen_build_python_utilities]
path = "../python_utilities"
