
macos_arm_task:
  name: Publish arm m1 version of tools
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  only_if: $CIRRUS_RELEASE != ''
  script: arch -arm64 ./.cirrus/publish-macos-m1-build.sh
  env:
    GITHUB_TOKEN: ENCRYPTED[a774c234c21c929b2200ecd89cfb0be3c5b05f6517d5248c436d5435c342e89272867a0d9c13db45274e5f7228e3c912]
