name: Test
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add rustfmt
      - run: cd crates; cargo test --all-features
      - run: cd crates; cargo test
      - run: cd language_generators/scala-defref-extractor; ./sbt test
      - run: ./prepare_all_apps.sh
