name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: ${{ runner.os == 'Linux' }}
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools # provides musl-gcc
          version: 1.0
      - run: rustup component add rustfmt
      - if: ${{ runner.os == 'Linux' }}
        run: rustup target add x86_64-unknown-linux-musl
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - run: cd crates; cargo test --all-features
      - run: cd crates; cargo test
      - run: cd language_generators/scala-defref-extractor; ./sbt "test; scalafmtCheckAll"
      - run: ./prepare_all_apps.sh
