# name: Test
# on:
#   push:
# jobs:
#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: true
#       matrix:
#         os: [macos-latest, ubuntu-latest]
#         include:
#           - os: macos-latest
#             platform: macos
#           - os: ubuntu-latest
#             platform: linux
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Protoc
#         uses: arduino/setup-protoc@v1
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#       - run: rustup component add rustfmt
#       - run: cd crates; cargo test --all-features
#       - run: cd crates; cargo test
