name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-latest
            platform: macos
            jobtype: 1
          - os: macos-latest
            platform: macos
            jobtype: 3
          - os: ubuntu-latest
            platform: linux
            jobtype: 1
          - os: ubuntu-latest
            platform: linux
            jobtype: 2
          - os: ubuntu-latest
            platform: linux
            jobtype: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: ${{ runner.os == 'Linux' }}
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools # provides musl-gcc
          version: 1.0
      - run: rustup component add rustfmt
      - if: ${{ runner.os == 'Linux' }}
        run: rustup target add x86_64-unknown-linux-musl
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-${{ hashFiles('**/.bazelrc', '**/.bazeliskrc', '**/WORKSPACE', '**/WORKSPACE.bazel', '**/MODULE.bazel') }}
      - if: ${{ matrix.jobtype == 1 }}
        run: cd crates; cargo test --all-features
      - if: ${{ matrix.jobtype == 1 }}
        run: cd crates; cargo test
      - if: ${{ matrix.jobtype == 2 }}
        run: cd language_generators/scala-defref-extractor; ./sbt "test; scalafmtCheckAll"
      - if: ${{ matrix.jobtype == 3 }}
        run: |
          ./prepare_all_apps.sh
          .github/ci_scripts/integration_test.sh
